HALF - Restructure half.hpp and hip_fp16.h includes (#459)
* Add includes for half in rpp_defs
> Remove the Repeating half includes

* revert changes in old test suite

* Update rpp_test_suite_image.h to fix redefinition error

Error:
" In file included from /opt/rocm-6.3.0/share/rpp/test/HIP/Tensor_hip.cpp:33:
2989
4: /opt/rocm-6.3.0/share/rpp/test/HIP/../rpp_test_suite_image.h:53:14: error: typedef redefinition with different types ('half' (aka '__half') vs 'halfhpp' (aka 'half_float::half'))
2990
4:    53 | typedef half Rpp16f;
2991
4:       |              ^
2992
4: /opt/rocm/include/rpp/rppdefs.h:41:17: note: previous definition is here
2993
4:    41 | typedef halfhpp Rpp16f;
2994
4:       |                 ^
2995
4: 1 error generated when compiling for gfx942."

---------

Co-authored-by: HazarathKumarM <hazarathkumar@multicorewareinc.com>
Co-authored-by: Kiriti Gowda <kiritigowda@gmail.com>